-- MySQL Script generated by MySQL Workbench
-- Sat Nov  3 02:28:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_kn_ledger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_kn_ledger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_kn_ledger` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `db_kn_ledger` ;

-- -----------------------------------------------------
-- Table `db_kn_ledger`.`tbl_currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kn_ledger`.`tbl_currency` (
  `id` INT UNSIGNED NOT NULL,
  `info` TEXT NOT NULL COMMENT 'Currency information',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_kn_ledger`.`tbl_wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kn_ledger`.`tbl_wallet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `currency_id` INT UNSIGNED NOT NULL COMMENT 'Currency that wallet holds. A wallet cannot hold more than one currency.',
  `info` TEXT NOT NULL COMMENT 'Wallet information like its name.',
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_wallet_tbl_currency1_idx` (`currency_id` ASC),
  CONSTRAINT `fk_tbl_wallet_tbl_currency1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `db_kn_ledger`.`tbl_currency` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_kn_ledger`.`tbl_ledger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kn_ledger`.`tbl_ledger` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `wallet_id` INT UNSIGNED NOT NULL COMMENT 'Source wallet ID that is having the transaction.',
  `tx` TEXT NOT NULL COMMENT 'Encrypted Transaction Information',
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_ledger_tbl_wallet_idx` (`wallet_id` ASC),
  CONSTRAINT `fk_tbl_ledger_tbl_wallet`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `db_kn_ledger`.`tbl_wallet` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
