-- MySQL Script generated by MySQL Workbench
-- Sun Nov  4 23:07:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_tool_login
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tool_login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tool_login` DEFAULT CHARACTER SET utf8 ;
USE `db_tool_login` ;

-- -----------------------------------------------------
-- Table `db_tool_login`.`tbl_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tool_login`.`tbl_login` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL COMMENT 'Hashed username (sha256)',
  `password` VARCHAR(60) NOT NULL COMMENT 'Salted hashed password',
  `rights` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Rights granted to user.',
  `key` VARCHAR(44) NULL COMMENT 'Secret key designated for encrypting sensitive information. Key is shared across all users. Key is decrypted with user password.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
